// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SABBglfVBqpNlYq4MqGHiRHGvgG3bAY',
    appId: '1:649631558750:web:d1d60d050d20848f2f98cf',
    messagingSenderId: '649631558750',
    projectId: 'verifydtn',
    authDomain: 'verifydtn.firebaseapp.com',
    storageBucket: 'verifydtn.appspot.com',
    measurementId: 'G-VRFCS7QGSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLL07N87VBFi3fsMSMr2kL5kNMmmPzL74',
    appId: '1:649631558750:android:31bfc16c3a35879d2f98cf',
    messagingSenderId: '649631558750',
    projectId: 'verifydtn',
    storageBucket: 'verifydtn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIutlffOmOX_iDynuG4lnr0lA7LpQvqXQ',
    appId: '1:649631558750:ios:79a5b4031d933d872f98cf',
    messagingSenderId: '649631558750',
    projectId: 'verifydtn',
    storageBucket: 'verifydtn.appspot.com',
    iosBundleId: 'com.example.dtn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIutlffOmOX_iDynuG4lnr0lA7LpQvqXQ',
    appId: '1:649631558750:ios:90c1eb4934d370e72f98cf',
    messagingSenderId: '649631558750',
    projectId: 'verifydtn',
    storageBucket: 'verifydtn.appspot.com',
    iosBundleId: 'com.example.dtn.RunnerTests',
  );
}
